# Compost (design-v11 §16.6): slatted box with a propped lid, 1.2 x 1.0 m; compost_worm peeks out now and then;
# spot_peg marks the place before it is built (also used for the hive). Steam = game Points at the attach points.
exec(open(LIB + '/props_common.py').read(), globals())
exec(open(LIB + '/crops.py').read(), globals())
exec(open(LIB + '/extras.py').read(), globals())
reset()
ob = build_compost()
worm = build_worm()
peg = build_spot_peg()
attach(ob, 'attach_steam_lid', (0.0, -0.1, 0.7))
attach(ob, 'attach_steam_gap_l', (-0.6, 0.0, 0.47))
attach(ob, 'attach_steam_gap_r', (0.6, 0.15, 0.33))
attach(ob, 'attach_worm', (-0.3, -0.32, 0.58))
objs = [ob, worm, peg]
fit_all(objs, {'compost': 1900})
report(objs)
save_blend('compost')
to_origin(objs)
export_glb(objs, f'{GLB_DIR}/compost.glb')
worm.location = (-0.3, -0.32, 0.58)
peg.location = (1.0, -0.3, 0)
preview(objs, f'{PNG_DIR}/compost.png', yaw=-28, pitch=24, margin=0.8)
worm.location = (0, 0, 0)
peg.location = (0, 0, 0)
spread(objs, 0.3)
save_blend('compost')
print('FINAL compost', {o.name: tris(o) for o in objs})
